openapi: 3.0.0
info:
  version: "1"
  title: CTF2026 API
  description: API for Capture the Flag 2026
  x-apiname: CTF2026
servers:
  - url: https://mainframeyin:8092/CTF2026/API/v1
paths:
  /loginInfo:
    summary: Get login information for current user
    get:
      summary: Get login information for current user
      responses:
        '200':
          description: Successful retrieval of login information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/loginInfo"
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal server error
        default:
          description: Unexpected error
      x-LWWProcessingSteps:
        - AllocateIOArea:
            name: LCTFC100
            initWith: 0x00
            size: 272
            fields:
              $ref: "#/components/x-ioareas/LCTFC100"
        - Link:
            program: CTFC100
            passDataWith: container
            ioArea:
              $ref: "#/paths/~1loginInfo/get/x-LWWProcessingSteps/0/AllocateIOArea"
        - CreateObject:
            name: CTFC100_RESP
            properties:
              $ref: "#/components/schemas/loginInfo/properties"
        - Mapping:
            from:
              $ref: "#/paths/~1loginInfo/get/x-LWWProcessingSteps/0/AllocateIOArea/fields"
            to:
              $ref: "#/paths/~1loginInfo/get/x-LWWProcessingSteps/2/CreateObject/properties"
            combinations:
              - type: singleFields
                fromName: USERID
                toName: userid
              - type: singleFields
                fromName: NICKNAME
                toName: nickname
        - JSONWriter:
            responseObject:
              $ref: "#/paths/~1loginInfo/get/x-LWWProcessingSteps/2/CreateObject"
components:
  schemas:
    loginInfo:
      type: object
      properties:
        userid:
          type: string
        nickname:
          type: string
  x-ioareas:
    LCTFC100:
      fields:
        - name: USERID
          type: CHARARRAY1200
          length: 8
        - name: NICKNAME
          type: VARCHAR1200
          length: 128